env:
  browser: true
  es2021: true
extends: airbnb-base
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {
  linebreak-style: ["error", "windows"],
  max-len: ["error", {
    "code": 140,
    "comments": 140
  }],
  no-plusplus: 0,
  no-use-before-define: 0
}
